site_name: F-15E Workbooks
site_url: https://deux2k5.github.io/Workbooks/
theme:
  name: material
  logo: assets/images/Logo/391Logo.png
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - AAM - Aerial Attack Maneuvering: aam/index.md
  - AAW - Air-to-Air Weapons: aaw/index.md
  - ACG - Aircraft General: acg/index.md
  - AGD - Air-to-Ground Delivery: agd/index.md
  - AGR - Air-to-Ground Radar: agr/index.md
  - AGW - Air-to-Ground Weapons: agw/index.md
  - AVI - Avionics: avi/index.md
  - EW - Electronic Warfare: ew/index.md
  - LAN - LANTIRN: lan/index.md
  - OPS - Operations: ops/index.md
  - RDR - Radar: rdr/index.md
  - TAC - Tactics: tac/index.md
  - Hierarchy - Sensor Hierarchy: hierarchy/index.md